const KEY='mva-production-workspace-v1';
const EMPTY={patients:[],appointments:[],tasks:[],followups:[],billing:[],insurance:[],documents:[],messages:[],activity:[]};
function fresh(){return JSON.parse(JSON.stringify(EMPTY))}
function save(){localStorage.setItem(KEY,JSON.stringify(db))}
let db=JSON.parse(localStorage.getItem(KEY)||'null')||fresh();
if(db.patients?.some(p=>/Maria Santos|Daniel Reyes|Sophia Cruz|Michael Garcia|Anna Rodriguez/i.test(p.name||''))){db=fresh();save()}
let view='dashboard';
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2300)}
function initials(n=''){return n.split(' ').map(x=>x[0]).join('').slice(0,2)}function badge(s){let c=/completed|active|verified|paid/i.test(s)?'green':/pending|scheduled|progress|due|submitted/i.test(s)?'amber':/high|unread|rejected/i.test(s)?'red':'blue';return `<span class="badge ${c}">${esc(s)}</span>`}
function head(title,sub,button='',action=''){return `<div class="page-head"><div><h1>${title}</h1><p>${sub}</p></div>${button?`<div class="actions"><button class="btn primary" onclick="${action}">${button}</button></div>`:''}</div>`}
function table(headers,rows){return `<table class="table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows||`<tr><td colspan="${headers.length}" class="empty">No records found</td></tr>`}</tbody></table>`}
function dashboard(){let open=db.tasks.filter(x=>x.status!=='Completed').length,claims=db.billing.filter(x=>x.status!=='Paid').length,today=new Date().toISOString().slice(0,10);return head('Workspace','Operational overview for today.','＋ Add Patient','openPatient()')+`<div class="stats"><button class="stat" onclick="view='patients';render()"><div class="stat-top"><span>Total Patients</span><span class="stat-icon">♙</span></div><strong>${db.patients.length}</strong><span class="trend">● Active workspace</span></button><button class="stat" onclick="view='appointments';render()"><div class="stat-top"><span>Today’s Appointments</span><span class="stat-icon">◷</span></div><strong>${db.appointments.filter(x=>x.date===today).length}</strong><span class="trend">Scheduled & completed</span></button><button class="stat" onclick="view='tasks';render()"><div class="stat-top"><span>Open Tasks</span><span class="stat-icon">✓</span></div><strong>${open}</strong><span class="trend">Action required</span></button><button class="stat" onclick="view='billing';render()"><div class="stat-top"><span>Outstanding Claims</span><span class="stat-icon">₱</span></div><strong>${claims}</strong><span class="trend">Tracking enabled</span></button></div><div class="grid2"><div class="card"><div class="card-head"><h3>Upcoming appointments</h3><button class="btn" onclick="view='appointments';render()">View all</button></div>${table(['Patient','Type','Time','Provider','Status'],db.appointments.filter(x=>x.date===today).map(x=>`<tr><td><div class="patient"><span class="mini-avatar">${initials(x.patient)}</span>${esc(x.patient)}</div></td><td>${esc(x.type)}</td><td>${esc(x.time)}</td><td>${esc(x.provider)}</td><td>${badge(x.status)}</td></tr>`).join(''))}</div><div class="card"><div class="card-head"><h3>Recent activity</h3><button class="btn" onclick="view='activity';render()">View all</button></div><div class="activity">${db.activity.slice(0,6).map(x=>`<div class="event"><i class="event-dot"></i><div><b>${esc(x.text)}</b><p>${esc(x.time)} · ${esc(x.type)}</p></div></div>`).join('')||'<div class="empty">No activity yet</div>'}</div></div></div><button class="card workflow" onclick="view='automations';render()"><div class="card-head" style="margin:-17px -18px 17px"><h3>Automated appointment workflow</h3><span>Connected process</span></div><div class="flow">${[['1','Appointment','Completed'],['2','Billing','Created'],['3','Insurance','Checked'],['4','Task','Created'],['5','Notify','Staff alert'],['6','Claim','Tracked']].map((x,i)=>(i?'<span class="arrow">›</span>':'')+`<div class="flow-step"><div class="circle">${x[0]}</div><b>${x[1]}</b><small>${x[2]}</small></div>`).join('')}</div></button>`}
function patients(){return head('Patients','Manage patient records and activity.','＋ Add Patient','openPatient()')+`<div class="toolbar"><input class="filter search-wide" id="patientSearch" placeholder="Search patients..." oninput="filterRows(this.value,'patientTable')"><select class="filter" onchange="filterRows(this.value==='All statuses'?'':this.value,'patientTable')"><option>All statuses</option><option>Active</option><option>Follow-up</option><option>Pending</option></select></div><div class="card" id="patientTable">${table(['Patient ID','Patient','Age','Sex','Status','Action'],db.patients.map(x=>`<tr><td>${x.id}</td><td><div class="patient"><span class="mini-avatar">${initials(x.name)}</span><b>${esc(x.name)}</b></div></td><td>${x.age}</td><td>${x.sex}</td><td>${badge(x.status)}</td><td><button class="btn" onclick="patientInfo('${x.id}')">View</button></td></tr>`).join(''))}</div>`}
function appointments(){let today=new Date().toISOString().slice(0,10);return head('Appointments','Schedule, track, and complete visits.','＋ Add Appointment','openAppointment()')+`<div class="card">${table(['ID','Patient','Appointment','Date','Time','Provider','Status','Action'],db.appointments.map(x=>`<tr><td>${x.id}</td><td>${esc(x.patient)}</td><td>${esc(x.type)}</td><td>${x.date}</td><td>${x.time}</td><td>${esc(x.provider)}</td><td>${badge(x.status)}</td><td>${x.status==='Scheduled'?`<button class="btn primary" onclick="completeAppointment('${x.id}')">Complete</button>`:'—'}</td></tr>`).join(''))}</div>`}
function followups(){return head('Follow-ups','Keep post-visit and care coordination actions on schedule.','＋ Add Follow-up','openFollowup()')+`<div class="card">${table(['ID','Patient','Due','Reason','Status','Action'],db.followups.map(x=>`<tr><td>${x.id}</td><td>${esc(x.patient)}</td><td>${x.due}</td><td>${esc(x.reason)}</td><td>${badge(x.status)}</td><td><button class="btn" onclick="markFollow('${x.id}')">${x.status==='Completed'?'Completed':'Mark done'}</button></td></tr>`).join(''))}</div>`}
function tasks(){return head('Tasks','Centralized operational work queue.','＋ Add Task','openTask()')+`<div class="card">${table(['Task','Patient','Priority','Status','Action'],db.tasks.map(x=>`<tr><td><b>${esc(x.title)}</b></td><td>${esc(x.patient)}</td><td>${badge(x.priority)}</td><td>${badge(x.status)}</td><td><button class="btn" onclick="completeTask('${x.id}')">${x.status==='Completed'?'Done':'Complete'}</button></td></tr>`).join(''))}</div>`}
function automations(){return head('Automations','Rules that connect work across the system.','＋ New Automation','openAutomation()')+`<div class="report-grid"><div class="card report-card"><span>APPOINTMENT COMPLETED</span><strong>→ 5 actions</strong><p>Billing record, insurance check, task, staff notification and claim tracking.</p><button class="btn primary" onclick="toast('Workflow is active')">Active</button></div><div class="card report-card"><span>FOLLOW-UP DUE</span><strong>→ 2 actions</strong><p>Create task and notify assigned staff when a follow-up reaches its due date.</p><button class="btn primary" onclick="toast('Automation tested successfully')">Test</button></div><div class="card report-card"><span>NEW DOCUMENT</span><strong>→ 2 actions</strong><p>Attach to patient record and create an activity entry for the care team.</p><button class="btn primary" onclick="toast('Automation is active')">Active</button></div></div>`}
function messages(){return head('Messages','Internal communication and notifications.','＋ New Message','openMessage()')+`<div class="card">${table(['From','Subject','Patient','Time','Status','Action'],db.messages.map(x=>`<tr><td>${esc(x.from)}</td><td><b>${esc(x.subject)}</b></td><td>${esc(x.patient)}</td><td>${x.time}</td><td>${badge(x.status)}</td><td><button class="btn" onclick="readMessage('${x.id}')">Open</button></td></tr>`).join(''))}</div>`}
function billing(){return head('Billing','Claims, payments, and outstanding balances.','＋ New Billing Record','openBilling()')+`<div class="stats"><button class="stat"><span class="stat-top">Outstanding</span><strong>₱${db.billing.filter(x=>x.status!=='Paid').reduce((a,x)=>a+Number(x.amount||0),0).toLocaleString()}</strong></button><button class="stat"><span class="stat-top">Claims tracked</span><strong>${db.billing.length}</strong></button><button class="stat"><span class="stat-top">Submitted</span><strong>${db.billing.filter(x=>/submitted/i.test(x.status)).length}</strong></button><button class="stat"><span class="stat-top">Paid</span><strong>${db.billing.filter(x=>x.status==='Paid').length}</strong></button></div><div class="card">${table(['Claim','Patient','Amount','Status','Action'],db.billing.map(x=>`<tr><td>${esc(x.claim)}</td><td>${esc(x.patient)}</td><td>₱${Number(x.amount||0).toLocaleString()}</td><td>${badge(x.status)}</td><td><button class="btn" onclick="markPaid('${x.id}')">Mark paid</button></td></tr>`).join(''))}</div>`}
function insurance(){return head('Insurance','Eligibility checks and payer status.','＋ Run Insurance Check','runInsurance()')+`<div class="card">${table(['Patient','Provider','Status','Last check','Action'],db.insurance.map(x=>`<tr><td>${esc(x.patient)}</td><td>${esc(x.provider)}</td><td>${badge(x.status)}</td><td>${x.lastCheck}</td><td><button class="btn" onclick="checkInsurance('${esc(x.patient)}')">Check</button></td></tr>`).join(''))}</div>`}
function documents(){return head('Documents & Files','Upload, view, and manage files attached to records.','＋ Upload Files','openDocuments()')+`<div class="card"><div class="card-head"><h3>Patient and record documents</h3><span>${db.documents.length} file(s)</span></div>${table(['File','Type','Patient','Uploaded','Uploaded by','Actions'],db.documents.map(x=>`<tr><td><div class="patient"><span class="file-icon">${esc((x.type||'FILE').slice(0,3))}</span><b>${esc(x.name)}</b></div></td><td>${esc(x.type)}</td><td>${esc(x.patient)}</td><td>${x.date}</td><td>${esc(x.owner)}</td><td><button class="btn" onclick="viewDoc('${x.id}')">View</button> <button class="btn" onclick="downloadDoc('${x.id}')">Download</button> <button class="btn danger" onclick="deleteDoc('${x.id}')">Delete</button></td></tr>`).join(''))}</div>`}
function reports(){let ap=Math.round(db.appointments.filter(x=>x.status==='Completed').length/Math.max(db.appointments.length,1)*100),ta=Math.round(db.tasks.filter(x=>x.status==='Completed').length/Math.max(db.tasks.length,1)*100);return head('Reports','Operational summaries generated from the current workspace.','Generate Report','generateReport()')+`<div class="report-grid"><div class="card report-card"><span>PATIENT ACTIVITY</span><strong>${db.patients.length}</strong><p>Patient records currently available.</p></div><div class="card report-card"><span>APPOINTMENT COMPLETION</span><strong>${ap}%</strong><p>Visits completed versus scheduled.</p></div><div class="card report-card"><span>TASK COMPLETION</span><strong>${ta}%</strong><p>Operational tasks completed.</p></div></div>`}
function activity(){return head('Activity','Chronological system and workflow activity.')+`<div class="card"><div class="activity">${db.activity.map(x=>`<div class="event"><i class="event-dot"></i><div><b>${esc(x.text)}</b><p>${esc(x.time)} · ${esc(x.type)}</p></div></div>`).join('')||'<div class="empty">No activity yet</div>'}</div></div>`}
const views={dashboard,patients,appointments,followups,tasks,automations,messages,billing,insurance,documents,reports,activity};
function render(){const fn=views[view]||dashboard;$('#content').innerHTML=fn();document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#pageTitle').textContent=view[0].toUpperCase()+view.slice(1);$('#pageKicker').textContent=view==='dashboard'?'Workspace':'Medical VA';}
function openModal(title,body,saveLabel,saveFn){$('#modalRoot').innerHTML=`<div class="modal-backdrop" onclick="if(event.target===this)closeModal()"><div class="modal"><div class="modal-head"><h3>${title}</h3><button class="icon-btn" onclick="closeModal()">×</button></div><div class="modal-body">${body}</div><div class="modal-actions"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="${saveFn}">${saveLabel}</button></div></div></div>`}
function closeModal(){$('#modalRoot').innerHTML=''}
function patientOptions(){return db.patients.map(p=>`<option value="${esc(p.name)}">${esc(p.name)}</option>`).join('')}
function requirePatients(){if(!db.patients.length){toast('Add a patient first');view='patients';render();return false}return true}
function nextId(prefix,arr){let n=arr.reduce((m,x)=>Math.max(m,parseInt(String(x.id||'').replace(/\D/g,''))||0),0)+1;return prefix+'-'+String(n).padStart(4,'0')}
function openPatient(){openModal('Add Patient',`<div class="form-grid"><label>Patient name<input id="pName" required></label><label>Age<input id="pAge" type="number" min="0"></label><label>Sex<select id="pSex"><option>Female</option><option>Male</option><option>Other</option><option>Prefer not to say</option></select></label><label>Status<select id="pStatus"><option>Active</option><option>Follow-up</option><option>Pending</option></select></label></div>`,'Save Patient','addPatient()')}
function addPatient(){let name=$('#pName').value.trim();if(!name){toast('Patient name is required');return}db.patients.push({id:nextId('P',db.patients),name,age:$('#pAge').value||'',sex:$('#pSex').value,status:$('#pStatus').value});log('Patient added: '+name,'Patients');save();closeModal();render();toast('Patient added')}
function openAppointment(){if(!requirePatients())return;openModal('Add Appointment',`<div class="form-grid"><label>Patient<select id="aPatient">${patientOptions()}</select></label><label>Appointment type<input id="aType" placeholder="Consultation"></label><label>Date<input id="aDate" type="date" value="${new Date().toISOString().slice(0,10)}"></label><label>Time<input id="aTime" type="time"></label><label>Provider<input id="aProvider" placeholder="Provider name"></label></div>`,'Save Appointment','addAppointment()')}
function addAppointment(){let patient=$('#aPatient').value;if(!patient){toast('Select a patient');return}db.appointments.push({id:nextId('A',db.appointments),patient,type:$('#aType').value.trim()||'Appointment',date:$('#aDate').value,time:$('#aTime').value,provider:$('#aProvider').value.trim(),status:'Scheduled'});log('Appointment scheduled for '+patient,'Appointments');save();closeModal();render();toast('Appointment added')}
function openTask(){if(!requirePatients())return;openModal('Add Task',`<div class="form-grid"><label>Task<input id="tTitle" placeholder="Task description"></label><label>Patient<select id="tPatient">${patientOptions()}</select></label><label>Priority<select id="tPriority"><option>High</option><option>Medium</option><option>Low</option></select></label></div>`,'Save Task','addTask()')}
function addTask(){let title=$('#tTitle').value.trim();if(!title){toast('Task title is required');return}db.tasks.push({id:nextId('T',db.tasks),title,patient:$('#tPatient').value,priority:$('#tPriority').value,status:'Open'});log('Task created: '+title,'Tasks');save();closeModal();render();toast('Task added')}
function openFollowup(){if(!requirePatients())return;openModal('Add Follow-up',`<div class="form-grid"><label>Patient<select id="fPatient">${patientOptions()}</select></label><label>Due date<input id="fDue" type="date"></label><label>Reason<input id="fReason" placeholder="Reason for follow-up"></label></div>`,'Save Follow-up','addFollowup()')}
function addFollowup(){db.followups.push({id:nextId('F',db.followups),patient:$('#fPatient').value,due:$('#fDue').value,reason:$('#fReason').value.trim(),status:'Pending'});log('Follow-up created for '+$('#fPatient').value,'Follow-ups');save();closeModal();render();toast('Follow-up added')}
function openBilling(){if(!requirePatients())return;openModal('New Billing Record',`<div class="form-grid"><label>Patient<select id="bPatient">${patientOptions()}</select></label><label>Amount<input id="bAmount" type="number" min="0"></label><label>Claim ID<input id="bClaim" placeholder="Claim reference"></label><label>Status<select id="bStatus"><option>Pending</option><option>Claim submitted</option><option>Paid</option></select></label></div>`,'Save Billing','addBilling()')}
function addBilling(){db.billing.push({id:nextId('B',db.billing),patient:$('#bPatient').value,amount:Number($('#bAmount').value||0),status:$('#bStatus').value,claim:$('#bClaim').value.trim()||nextId('CLM',db.billing)});log('Billing record created for '+$('#bPatient').value,'Billing');save();closeModal();render();toast('Billing record added')}
function openDocuments(){if(!requirePatients())return;openModal('Upload Files',`<label>Patient<select id="dPatient">${patientOptions()}</select></label><label class="dropzone">Choose one or more files<input id="dFiles" type="file" multiple accept=".pdf,.doc,.docx,.xls,.xlsx,.csv,.txt,image/*"></label>`,'Upload','uploadFiles()')}
function uploadFiles(){let files=[...($('#dFiles').files||[])];if(!files.length){toast('Select at least one file');return}files.forEach(f=>db.documents.push({id:nextId('D',db.documents),name:f.name,type:f.type||'FILE',date:new Date().toISOString().slice(0,10),owner:'Administrator',patient:$('#dPatient').value}));log(files.length+' document(s) uploaded','Documents');save();closeModal();render();toast(files.length+' file(s) added')}
function patientInfo(id){let p=db.patients.find(x=>x.id===id);if(!p)return;openModal('Patient Record',`<div class="detail"><p><b>Patient ID:</b> ${esc(p.id)}</p><p><b>Name:</b> ${esc(p.name)}</p><p><b>Age:</b> ${esc(p.age)}</p><p><b>Sex:</b> ${esc(p.sex)}</p><p><b>Status:</b> ${badge(p.status)}</p></div>`,'Close','closeModal()')}
function completeAppointment(id){let a=db.appointments.find(x=>x.id===id);if(!a)return;a.status='Completed';let claim=nextId('CLM',db.billing);db.billing.push({id:nextId('B',db.billing),patient:a.patient,amount:0,status:'Claim submitted',claim});db.insurance.push({patient:a.patient,provider:'Pending payer',status:'Pending',lastCheck:new Date().toISOString().slice(0,10)});db.tasks.push({id:nextId('T',db.tasks),title:'Process completed appointment claim',patient:a.patient,priority:'High',status:'Open'});db.messages.push({id:nextId('M',db.messages),from:'System',subject:'Appointment completed — workflow started',patient:a.patient,time:'Now',status:'Unread'});log('Appointment '+a.id+' completed for '+a.patient,'Workflow');save();render();toast('Appointment completed — workflow started')}
function completeTask(id){let t=db.tasks.find(x=>x.id===id);if(!t)return;t.status='Completed';log('Task completed: '+t.title,'Tasks');save();render();toast('Task completed')}
function markFollow(id){let f=db.followups.find(x=>x.id===id);if(!f)return;f.status='Completed';log('Follow-up completed for '+f.patient,'Follow-ups');save();render();toast('Follow-up completed')}
function markPaid(id){let b=db.billing.find(x=>x.id===id);if(!b)return;b.status='Paid';log('Payment recorded for '+b.patient,'Billing');save();render();toast('Marked as paid')}
function checkInsurance(patient){let x=db.insurance.find(i=>i.patient===patient);if(!x){x={patient,provider:'Pending payer',status:'Pending',lastCheck:''};db.insurance.push(x)}x.status='Verified';x.lastCheck=new Date().toISOString().slice(0,10);log('Insurance eligibility checked for '+patient,'Insurance');save();render();toast('Insurance checked')}
function runInsurance(){if(!db.patients.length){toast('Add a patient first');view='patients';render();return}db.patients.forEach(p=>checkInsuranceSilent(p.name));save();render();toast('Insurance checks completed')}
function checkInsuranceSilent(patient){let x=db.insurance.find(i=>i.patient===patient);if(!x){x={patient,provider:'Pending payer'};db.insurance.push(x)}x.status='Verified';x.lastCheck=new Date().toISOString().slice(0,10)}
function viewDoc(id){let d=db.documents.find(x=>x.id===id);if(!d)return;openModal('File',`<div class="detail"><p><b>Filename:</b> ${esc(d.name)}</p><p><b>Type:</b> ${esc(d.type)}</p><p><b>Patient:</b> ${esc(d.patient)}</p><p><b>Uploaded:</b> ${esc(d.date)}</p><p>File metadata is stored in this browser workspace. Full binary preview/storage will be enabled with the production backend.</p></div>`,'Close','closeModal()')}
function downloadDoc(id){let d=db.documents.find(x=>x.id===id);if(!d)return;toast('Binary download requires local browser file storage')}
function deleteDoc(id){if(!confirm('Delete this document record?'))return;db.documents=db.documents.filter(x=>x.id!==id);log('Document deleted','Documents');save();render();toast('Document deleted')}
function readMessage(id){let m=db.messages.find(x=>x.id===id);if(!m)return;m.status='Read';save();openModal(m.subject,`<div class="detail"><p><b>From:</b> ${esc(m.from)}</p><p><b>Patient:</b> ${esc(m.patient)}</p><p>${esc(m.subject)}</p></div>`,'Close','closeModal()')}
function generateReport(){let text=`Medical VA Workspace Report\nPatients: ${db.patients.length}\nAppointments: ${db.appointments.length}\nCompleted appointments: ${db.appointments.filter(x=>x.status==='Completed').length}\nOpen tasks: ${db.tasks.filter(x=>x.status!=='Completed').length}\nBilling records: ${db.billing.length}\nDocuments: ${db.documents.length}`;let blob=new Blob([text],{type:'text/plain'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='medical-va-workspace-report.txt';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Report generated')}
function openAutomation(){openModal('New Automation',`<div class="form-grid"><label>Automation name<input id="autoName" placeholder="Automation name"></label><label>Trigger<select id="autoTrigger"><option>Appointment completed</option><option>Follow-up due</option><option>New document</option><option>New patient</option></select></label></div>`,'Save Automation','saveAutomation()')}
function saveAutomation(){let n=$('#autoName').value.trim();if(!n){toast('Automation name is required');return}log('Automation created: '+n,'Automations');save();closeModal();render();toast('Automation saved')}
function openMessage(){if(!requirePatients())return;openModal('New Message',`<div class="form-grid"><label>Patient<select id="mPatient">${patientOptions()}</select></label><label>From<input id="mFrom" value="Administrator"></label><label>Subject<input id="mSubject"></label><label>Message<textarea id="mBody" rows="4"></textarea></label></div>`,'Send Message','saveMessage()')}
function saveMessage(){let subject=$('#mSubject').value.trim();if(!subject){toast('Subject is required');return}db.messages.push({id:nextId('M',db.messages),from:$('#mFrom').value.trim()||'Administrator',subject,patient:$('#mPatient').value,time:'Now',status:'Unread',body:$('#mBody').value.trim()});log('Message sent to staff for '+$('#mPatient').value,'Messages');save();closeModal();render();toast('Message created')}
function log(text,type){db.activity.unshift({time:new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}),text,type})}
function filterRows(q,id){let root=$('#'+id);if(!root)return;let query=String(q||'').toLowerCase();root.querySelectorAll('tbody tr').forEach(r=>r.style.display=r.textContent.toLowerCase().includes(query)?'':'none')}
$('#nav').addEventListener('click',e=>{let b=e.target.closest('.nav-item');if(!b)return;view=b.dataset.view;render();$('#sidebar').classList.remove('open')});$('#menu').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));
$('#globalSearch').addEventListener('input',e=>{let q=e.target.value.trim();if(!q)return;view='patients';render();filterRows(q,'patientTable')});
$('#notificationBtn').addEventListener('click',()=>{let unread=db.messages.filter(x=>x.status==='Unread').length;view='messages';render();toast(unread?`${unread} unread message(s)`:'No unread messages')});
$('#resetDemo').addEventListener('click',()=>{if(confirm('Clear all workspace records? This cannot be undone.')){db=fresh();save();render();toast('Workspace cleared')}});
render();
