/* Unified patient profile: all patient-linked operational records in one place. */
(function(){
  const addStyle=document.createElement('style');
  addStyle.textContent=`
    .patient-profile{display:grid;gap:16px}.patient-profile-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.patient-profile-card{border:1px solid var(--line);border-radius:12px;background:#fbfcfe;padding:15px}.patient-profile-card h4{margin:0 0 10px;font-size:13px}.patient-profile-card p{margin:5px 0;font-size:11px;color:#68758a}.patient-profile-card strong{color:#172033}.patient-profile-wide{grid-column:1/-1}.profile-table{width:100%;border-collapse:collapse}.profile-table th,.profile-table td{padding:8px;border-bottom:1px solid #edf1f5;text-align:left;font-size:10px}.profile-table th{font-size:8px;text-transform:uppercase;color:#8b96a8}.profile-actions{display:flex;gap:8px;flex-wrap:wrap}.profile-doc{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:9px;border:1px solid #e7ebf2;border-radius:8px;background:#fff;margin-top:7px}.profile-doc small{color:#748096}.profile-empty{font-size:10px;color:#8b96a8;padding:8px 0}.profile-viewer{width:min(1000px,96vw);height:min(90vh,850px)}.profile-viewer .modal-body{height:calc(100% - 116px);padding:0;background:#101827;display:grid;place-items:center}.profile-viewer iframe{width:100%;height:100%;border:0;background:#fff}.profile-viewer img{max-width:100%;max-height:100%;object-fit:contain}.profile-drop{border:2px dashed #cbd5e1;border-radius:10px;padding:18px;text-align:center;color:#718096;font-size:10px}.profile-drop input{display:block;margin:9px auto 0;font-size:10px}.profile-label{font-size:10px;font-weight:700;color:#68758a}
    @media(max-width:760px){.patient-profile-grid{grid-template-columns:1fr}.patient-profile-wide{grid-column:auto}}
  `;
  document.head.appendChild(addStyle);

  const escP=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const collection=(k)=>Array.isArray(db[k])?db[k]:[];
  const patientByName=name=>db.patients.find(p=>p.name===name);
  const nextId=(prefix,arr)=>prefix+'-'+String(arr.length+1).padStart(4,'0')+'-'+Date.now().toString().slice(-4);
  const patientDocs=p=>collection('documents').filter(d=>d.patient===p.name);
  const patientBilling=p=>collection('billing').filter(b=>b.patient===p.name);
  const patientInsurance=p=>collection('insurance').filter(i=>i.patient===p.name);
  const patientAppointments=p=>collection('appointments').filter(a=>a.patient===p.name);
  const patientTasks=p=>collection('tasks').filter(t=>t.patient===p.name);
  const patientFollowups=p=>collection('followups').filter(f=>f.patient===p.name);
  const patientNotes=p=>collection('notes').filter(n=>n.patient===p.name);

  function profileTable(headers,rows){return `<table class="profile-table"><thead><tr>${headers.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows||`<tr><td colspan="${headers.length}" class="profile-empty">No records yet</td></tr>`}</tbody></table>`}
  function profile(id){
    const p=db.patients.find(x=>x.id===id);if(!p)return;
    const bills=patientBilling(p), ins=patientInsurance(p), apps=patientAppointments(p), docs=patientDocs(p), tasks=patientTasks(p), follows=patientFollowups(p), notes=patientNotes(p);
    const total=bills.reduce((s,b)=>s+Number(b.amount||0),0), paid=bills.filter(b=>/paid/i.test(b.status)).reduce((s,b)=>s+Number(b.amount||0),0);
    const body=`<div class="patient-profile">
      <div class="patient-profile-card"><h4>Patient Information</h4><div class="patient-profile-grid"><p><strong>Patient ID:</strong> ${escP(p.id)}</p><p><strong>Status:</strong> ${escP(p.status)}</p><p><strong>Name:</strong> ${escP(p.name)}</p><p><strong>Age:</strong> ${escP(p.age||'—')}</p><p><strong>Sex:</strong> ${escP(p.sex||'—')}</p></div></div>
      <div class="patient-profile-grid">
        <div class="patient-profile-card"><h4>Insurance</h4>${profileTable(['Provider','Member ID','Group','Status','Last Check'],ins.map(i=>`<tr><td>${escP(i.provider)}</td><td>${escP(i.memberId||i.memberID||'—')}</td><td>${escP(i.group||'—')}</td><td>${badge(i.status||'Pending')}</td><td>${escP(i.lastCheck||'—')}</td></tr>`).join(''))}<div class="profile-actions"><button class="btn primary" data-profile-add-insurance="${escP(p.id)}">＋ Add / Update Insurance</button></div></div>
        <div class="patient-profile-card"><h4>Billing</h4><p><strong>Total billed:</strong> ₱${total.toLocaleString()} &nbsp; <strong>Paid:</strong> ₱${paid.toLocaleString()}</p>${profileTable(['Claim','Amount','Status'],bills.map(b=>`<tr><td>${escP(b.claim)}</td><td>₱${Number(b.amount||0).toLocaleString()}</td><td>${badge(b.status||'Waiting')}</td></tr>`).join(''))}<div class="profile-actions"><button class="btn primary" data-profile-add-billing="${escP(p.id)}">＋ Add Billing</button></div></div>
      </div>
      <div class="patient-profile-card"><h4>Appointments</h4>${profileTable(['Date','Time','Type','Provider','Status'],apps.map(a=>`<tr><td>${escP(a.date)}</td><td>${escP(a.time)}</td><td>${escP(a.type)}</td><td>${escP(a.provider)}</td><td>${badge(a.status||'Scheduled')}</td></tr>`).join(''))}<div class="profile-actions"><button class="btn primary" data-profile-add-appointment="${escP(p.id)}">＋ Add Appointment</button></div></div>
      <div class="patient-profile-card patient-profile-wide"><h4>Documents & Files</h4><div class="profile-drop">Add PDF, Word/document, image, or other file<input id="profileFiles" type="file" multiple accept=".pdf,.doc,.docx,.xls,.xlsx,.csv,.txt,image/*"></div><div id="profileFileList">${docs.map(d=>`<div class="profile-doc"><div><b>${escP(d.name)}</b><br><small>${escP(d.type||'File')} · ${escP(d.date||'')} · ${escP(d.owner||'VA Joy')}</small></div><div><button class="btn" data-profile-view-doc="${escP(d.id)}">View</button> <button class="btn danger" data-profile-delete-doc="${escP(d.id)}">Delete</button></div></div>`).join('')||'<div class="profile-empty">No files attached to this patient.</div>'}</div></div>
      <div class="patient-profile-grid"><div class="patient-profile-card"><h4>Tasks</h4>${profileTable(['Task','Priority','Status'],tasks.map(t=>`<tr><td>${escP(t.title)}</td><td>${badge(t.priority)}</td><td>${badge(t.status)}</td></tr>`).join(''))}</div><div class="patient-profile-card"><h4>Follow-ups</h4>${profileTable(['Due','Reason','Status'],follows.map(f=>`<tr><td>${escP(f.due)}</td><td>${escP(f.reason)}</td><td>${badge(f.status)}</td></tr>`).join(''))}</div></div>
      <div class="patient-profile-card"><h4>Notes</h4>${notes.map(n=>`<p><strong>${escP(n.date||'')}</strong> · ${escP(n.type||'shared')}<br>${escP(n.text)}</p>`).join('')||'<div class="profile-empty">No notes linked to this patient.</div>'}</div>
    </div>`;
    modal(`Patient Record — ${escP(p.name)}`,body,()=>{},'Close');
    const m=$('#modalRoot .modal');if(m)m.style.width='min(1050px,96vw)';
    const files=$('#profileFiles');if(files)files.addEventListener('change',e=>handleFiles(p,e.target.files));
  }

  function reopenProfile(patientId){closeModal();setTimeout(()=>profile(patientId),0)}
  function addInsurance(pid){const p=db.patients.find(x=>x.id===pid);if(!p)return;const old=patientInsurance(p)[0]||{};modal('Patient Insurance',`<div class="form-grid"><label class="field">Insurance provider<input id="piProvider" value="${escP(old.provider||'')}"></label><label class="field">Member / Policy ID<input id="piMember" value="${escP(old.memberId||old.memberID||'')}"></label><label class="field">Group number<input id="piGroup" value="${escP(old.group||'')}"></label><label class="field">Status<select id="piStatus"><option>Pending</option><option>Eligible</option><option>Verified</option><option>Inactive</option><option>Rejected</option></select></label><label class="field full">Notes<textarea id="piNotes">${escP(old.notes||'')}</textarea></label></div>`,()=>{const provider=$('#piProvider').value.trim();if(!provider){toast('Insurance provider is required');return false}const item={id:old.id||nextId('INS',db.insurance),patient:p.name,provider,memberId:$('#piMember').value.trim(),group:$('#piGroup').value.trim(),status:$('#piStatus').value,lastCheck:today(),notes:$('#piNotes').value.trim()};if(old.id){Object.assign(old,item)}else db.insurance.push(item);log('Insurance updated for '+p.name,'Insurance');save();toast('Insurance saved');setTimeout(()=>reopenProfile(pid),0)});if(old.status)$('#piStatus').value=old.status}
  function addBilling(pid){const p=db.patients.find(x=>x.id===pid);if(!p)return;modal('Patient Billing',`<div class="form-grid"><label class="field">Amount to bill<input id="pbAmount" type="number" min="0" step="0.01"></label><label class="field">Claim / Invoice ID<input id="pbClaim" placeholder="Optional"></label><label class="field">Billing status<select id="pbStatus"><option>Waiting</option><option>Pending</option><option>Claim submitted</option><option>Partially paid</option><option>Paid</option><option>Denied</option><option>Cancelled</option></select></label><label class="field">Service date<input id="pbDate" type="date" value="${today()}"></label><label class="field full">Billing notes<textarea id="pbNotes"></textarea></label></div>`,()=>{const amount=Number($('#pbAmount').value||0);if(amount<=0){toast('Enter the amount to bill');return false}db.billing.push({id:nextId('B',db.billing),patient:p.name,amount,claim:$('#pbClaim').value.trim()||nextId('CLM',db.billing),status:$('#pbStatus').value,serviceDate:$('#pbDate').value,notes:$('#pbNotes').value.trim()});log('Billing record added for '+p.name,'Billing');save();toast('Billing saved');setTimeout(()=>reopenProfile(pid),0)})}
  function addAppointmentForPatient(pid){const p=db.patients.find(x=>x.id===pid);if(!p)return;modal('Patient Appointment',`<div class="form-grid"><label class="field">Appointment type<input id="paType" value="Consultation"></label><label class="field">Date<input id="paDate" type="date" value="${today()}"></label><label class="field">Time<input id="paTime" type="time"></label><label class="field">Provider<input id="paProvider"></label><label class="field full">Notes<textarea id="paNotes"></textarea></label></div>`,()=>{db.appointments.push({id:nextId('A',db.appointments),patient:p.name,type:$('#paType').value.trim()||'Appointment',date:$('#paDate').value,time:$('#paTime').value,provider:$('#paProvider').value.trim(),status:'Scheduled',notes:$('#paNotes').value.trim()});log('Appointment added for '+p.name,'Appointments');save();toast('Appointment saved');setTimeout(()=>reopenProfile(pid),0)})}
  function handleFiles(p,files){if(!files||!files.length)return;Array.from(files).forEach(file=>{const reader=new FileReader();reader.onload=()=>{db.documents.push({id:nextId('DOC',db.documents),name:file.name,type:file.type||'File',patient:p.name,date:today(),owner:'VA Joy',size:file.size,dataUrl:reader.result});log('Document added for '+p.name+': '+file.name,'Documents');save();toast(file.name+' attached');reopenProfile(p.id)};reader.readAsDataURL(file)})}
  function viewDoc(id){const d=db.documents.find(x=>x.id===id);if(!d)return;if(!d.dataUrl){toast('This older file has no stored preview. Use Documents to replace it.');return}const image=/^image\//i.test(d.type);const pdf=d.type==='application/pdf'||/\.pdf$/i.test(d.name);const body=image?`<img src="${d.dataUrl}" alt="${escP(d.name)}">`:pdf?`<iframe src="${d.dataUrl}" title="${escP(d.name)}"></iframe>`:`<div style="background:#fff;padding:30px;text-align:center"><h3>${escP(d.name)}</h3><p>This file type cannot be previewed directly in the browser.</p><a class="btn primary" href="${d.dataUrl}" download="${escP(d.name)}">Download file</a></div>`;modal('File Viewer',body,()=>{},'Close');const m=$('#modalRoot .modal');if(m)m.classList.add('profile-viewer')}
  function deleteDoc(id){const d=db.documents.find(x=>x.id===id);if(!d||!confirm('Delete this file?'))return;db.documents=db.documents.filter(x=>x.id!==id);save();toast('File deleted');if(d.patient){const p=patientByName(d.patient);if(p)reopenProfile(p.id)}}
  function addPatient(){modal('Add Patient',`<div class="form-grid"><label class="field">Patient name<input id="upName"></label><label class="field">Age<input id="upAge" type="number"></label><label class="field">Sex<select id="upSex"><option>Female</option><option>Male</option><option>Other</option><option>Prefer not to say</option></select></label><label class="field">Status<select id="upStatus"><option>Active</option><option>Follow-up</option><option>Pending</option></select></label></div><hr><h4>Insurance Information</h4><div class="form-grid"><label class="field">Provider<input id="upInsProvider"></label><label class="field">Member / Policy ID<input id="upInsMember"></label><label class="field">Group number<input id="upInsGroup"></label><label class="field">Insurance status<select id="upInsStatus"><option>Pending</option><option>Eligible</option><option>Verified</option><option>Inactive</option></select></label></div><hr><h4>Billing</h4><div class="form-grid"><label class="field">Amount to bill<input id="upBillAmount" type="number" min="0" step="0.01"></label><label class="field">Billing status<select id="upBillStatus"><option>Waiting</option><option>Pending</option><option>Claim submitted</option><option>Paid</option><option>Partially paid</option><option>Denied</option></select></label><label class="field">Claim / Invoice ID<input id="upClaim"></label></div><hr><h4>Appointment</h4><div class="form-grid"><label class="field">Appointment type<input id="upApptType" placeholder="Consultation"></label><label class="field">Date<input id="upApptDate" type="date" value="${today()}"></label><label class="field">Time<input id="upApptTime" type="time"></label><label class="field">Provider<input id="upApptProvider"></label></div><hr><h4>Documents</h4><p class="profile-label">Attach PDF, Word/document, image, or other file(s) after the patient is created.</p>`,()=>{const name=$('#upName').value.trim();if(!name){toast('Patient name is required');return false}const p={id:nextId('P',db.patients),name,age:$('#upAge').value,sex:$('#upSex').value,status:$('#upStatus').value};db.patients.push(p);const provider=$('#upInsProvider').value.trim();if(provider)db.insurance.push({id:nextId('INS',db.insurance),patient:name,provider,memberId:$('#upInsMember').value.trim(),group:$('#upInsGroup').value.trim(),status:$('#upInsStatus').value,lastCheck:today()});const amount=Number($('#upBillAmount').value||0);if(amount>0)db.billing.push({id:nextId('B',db.billing),patient:name,amount,claim:$('#upClaim').value.trim()||nextId('CLM',db.billing),status:$('#upBillStatus').value,serviceDate:today()});const at=$('#upApptType').value.trim();if(at)db.appointments.push({id:nextId('A',db.appointments),patient:name,type:at,date:$('#upApptDate').value,time:$('#upApptTime').value,provider:$('#upApptProvider').value.trim(),status:'Scheduled'});log('Patient added: '+name,'Patients');save();render();toast('Patient and linked information saved');return true},'Create Patient');}

  document.addEventListener('click',e=>{
    const add=e.target.closest('[data-action="add-patient"]');if(add){e.preventDefault();e.stopImmediatePropagation();addPatient();return}
    const pv=e.target.closest('[data-patient]');if(pv){e.preventDefault();e.stopImmediatePropagation();profile(pv.dataset.patient);return}
    const ai=e.target.closest('[data-profile-add-insurance]');if(ai){e.preventDefault();e.stopImmediatePropagation();addInsurance(ai.dataset.profileAddInsurance);return}
    const ab=e.target.closest('[data-profile-add-billing]');if(ab){e.preventDefault();e.stopImmediatePropagation();addBilling(ab.dataset.profileAddBilling);return}
    const aa=e.target.closest('[data-profile-add-appointment]');if(aa){e.preventDefault();e.stopImmediatePropagation();addAppointmentForPatient(aa.dataset.profileAddAppointment);return}
    const vd=e.target.closest('[data-profile-view-doc]');if(vd){e.preventDefault();e.stopImmediatePropagation();viewDoc(vd.dataset.profileViewDoc);return}
    const dd=e.target.closest('[data-profile-delete-doc]');if(dd){e.preventDefault();e.stopImmediatePropagation();deleteDoc(dd.dataset.profileDeleteDoc);return}
  },true);
})();
